// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: v1/auth_event.proto

package events

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthCreated) Reset() {
	*x = AuthCreated{}
	mi := &file_v1_auth_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthCreated) ProtoMessage() {}

func (x *AuthCreated) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthCreated.ProtoReflect.Descriptor instead.
func (*AuthCreated) Descriptor() ([]byte, []int) {
	return file_v1_auth_event_proto_rawDescGZIP(), []int{0}
}

func (x *AuthCreated) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthCreated) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthCreated) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_v1_auth_event_proto protoreflect.FileDescriptor

const file_v1_auth_event_proto_rawDesc = "" +
	"\n" +
	"\x13v1/auth_event.proto\x12\aauth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"t\n" +
	"\vAuthCreated\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB,Z*auth-service/internal/app/events/v1;eventsb\x06proto3"

var (
	file_v1_auth_event_proto_rawDescOnce sync.Once
	file_v1_auth_event_proto_rawDescData []byte
)

func file_v1_auth_event_proto_rawDescGZIP() []byte {
	file_v1_auth_event_proto_rawDescOnce.Do(func() {
		file_v1_auth_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_auth_event_proto_rawDesc), len(file_v1_auth_event_proto_rawDesc)))
	})
	return file_v1_auth_event_proto_rawDescData
}

var file_v1_auth_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_auth_event_proto_goTypes = []any{
	(*AuthCreated)(nil),         // 0: auth.v1.AuthCreated
	(*timestamp.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_v1_auth_event_proto_depIdxs = []int32{
	1, // 0: auth.v1.AuthCreated.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_auth_event_proto_init() }
func file_v1_auth_event_proto_init() {
	if File_v1_auth_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_auth_event_proto_rawDesc), len(file_v1_auth_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_auth_event_proto_goTypes,
		DependencyIndexes: file_v1_auth_event_proto_depIdxs,
		MessageInfos:      file_v1_auth_event_proto_msgTypes,
	}.Build()
	File_v1_auth_event_proto = out.File
	file_v1_auth_event_proto_goTypes = nil
	file_v1_auth_event_proto_depIdxs = nil
}
