// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: v1/user_address_api.proto

package apis

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserAddressService_CreateAddress_FullMethodName   = "/user.v1.UserAddressService/CreateAddress"
	UserAddressService_GetAllAddresses_FullMethodName = "/user.v1.UserAddressService/GetAllAddresses"
)

// UserAddressServiceClient is the client API for UserAddressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserAddressServiceClient interface {
	CreateAddress(ctx context.Context, in *CreateUserAddressRequest, opts ...grpc.CallOption) (*CreateUserAddressResponse, error)
	GetAllAddresses(ctx context.Context, in *GetAllUserAddressesRequest, opts ...grpc.CallOption) (*GetAllUserAddressesResponse, error)
}

type userAddressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserAddressServiceClient(cc grpc.ClientConnInterface) UserAddressServiceClient {
	return &userAddressServiceClient{cc}
}

func (c *userAddressServiceClient) CreateAddress(ctx context.Context, in *CreateUserAddressRequest, opts ...grpc.CallOption) (*CreateUserAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserAddressResponse)
	err := c.cc.Invoke(ctx, UserAddressService_CreateAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAddressServiceClient) GetAllAddresses(ctx context.Context, in *GetAllUserAddressesRequest, opts ...grpc.CallOption) (*GetAllUserAddressesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllUserAddressesResponse)
	err := c.cc.Invoke(ctx, UserAddressService_GetAllAddresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserAddressServiceServer is the server API for UserAddressService service.
// All implementations must embed UnimplementedUserAddressServiceServer
// for forward compatibility.
type UserAddressServiceServer interface {
	CreateAddress(context.Context, *CreateUserAddressRequest) (*CreateUserAddressResponse, error)
	GetAllAddresses(context.Context, *GetAllUserAddressesRequest) (*GetAllUserAddressesResponse, error)
	mustEmbedUnimplementedUserAddressServiceServer()
}

// UnimplementedUserAddressServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserAddressServiceServer struct{}

func (UnimplementedUserAddressServiceServer) CreateAddress(context.Context, *CreateUserAddressRequest) (*CreateUserAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAddress not implemented")
}
func (UnimplementedUserAddressServiceServer) GetAllAddresses(context.Context, *GetAllUserAddressesRequest) (*GetAllUserAddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllAddresses not implemented")
}
func (UnimplementedUserAddressServiceServer) mustEmbedUnimplementedUserAddressServiceServer() {}
func (UnimplementedUserAddressServiceServer) testEmbeddedByValue()                            {}

// UnsafeUserAddressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserAddressServiceServer will
// result in compilation errors.
type UnsafeUserAddressServiceServer interface {
	mustEmbedUnimplementedUserAddressServiceServer()
}

func RegisterUserAddressServiceServer(s grpc.ServiceRegistrar, srv UserAddressServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserAddressServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserAddressService_ServiceDesc, srv)
}

func _UserAddressService_CreateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAddressServiceServer).CreateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAddressService_CreateAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAddressServiceServer).CreateAddress(ctx, req.(*CreateUserAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAddressService_GetAllAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUserAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAddressServiceServer).GetAllAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAddressService_GetAllAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAddressServiceServer).GetAllAddresses(ctx, req.(*GetAllUserAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserAddressService_ServiceDesc is the grpc.ServiceDesc for UserAddressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserAddressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.UserAddressService",
	HandlerType: (*UserAddressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAddress",
			Handler:    _UserAddressService_CreateAddress_Handler,
		},
		{
			MethodName: "GetAllAddresses",
			Handler:    _UserAddressService_GetAllAddresses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/user_address_api.proto",
}
