// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: v1/user_api.proto

package apis

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Bio            *wrappers.StringValue  `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	Sex            *wrappers.StringValue  `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Birthdate      *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Phone          *wrappers.StringValue  `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	ProfilePicture *wrappers.StringValue  `protobuf:"bytes,7,opt,name=profile_picture,json=profilePicture,proto3" json:"profile_picture,omitempty"`
	CreatedAt      *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamp.Timestamp   `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_v1_user_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_v1_user_api_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetBio() *wrappers.StringValue {
	if x != nil {
		return x.Bio
	}
	return nil
}

func (x *User) GetSex() *wrappers.StringValue {
	if x != nil {
		return x.Sex
	}
	return nil
}

func (x *User) GetBirthdate() *timestamp.Timestamp {
	if x != nil {
		return x.Birthdate
	}
	return nil
}

func (x *User) GetPhone() *wrappers.StringValue {
	if x != nil {
		return x.Phone
	}
	return nil
}

func (x *User) GetProfilePicture() *wrappers.StringValue {
	if x != nil {
		return x.ProfilePicture
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpsertUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthId        int64                  `protobuf:"varint,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Bio           *wrappers.StringValue  `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	Sex           *wrappers.StringValue  `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Birthdate     *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Phone         *wrappers.StringValue  `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertUserRequest) Reset() {
	*x = UpsertUserRequest{}
	mi := &file_v1_user_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertUserRequest) ProtoMessage() {}

func (x *UpsertUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertUserRequest.ProtoReflect.Descriptor instead.
func (*UpsertUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_api_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertUserRequest) GetAuthId() int64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

func (x *UpsertUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertUserRequest) GetBio() *wrappers.StringValue {
	if x != nil {
		return x.Bio
	}
	return nil
}

func (x *UpsertUserRequest) GetSex() *wrappers.StringValue {
	if x != nil {
		return x.Sex
	}
	return nil
}

func (x *UpsertUserRequest) GetBirthdate() *timestamp.Timestamp {
	if x != nil {
		return x.Birthdate
	}
	return nil
}

func (x *UpsertUserRequest) GetPhone() *wrappers.StringValue {
	if x != nil {
		return x.Phone
	}
	return nil
}

type UpsertUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertUserResponse) Reset() {
	*x = UpsertUserResponse{}
	mi := &file_v1_user_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertUserResponse) ProtoMessage() {}

func (x *UpsertUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertUserResponse.ProtoReflect.Descriptor instead.
func (*UpsertUserResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_api_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthId        int64                  `protobuf:"varint,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_v1_user_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserRequest) GetAuthId() int64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_v1_user_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthId        int64                  `protobuf:"varint,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	Name          *wrappers.StringValue  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Bio           *wrappers.StringValue  `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	Sex           *wrappers.StringValue  `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Birthdate     *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Phone         *wrappers.StringValue  `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_v1_user_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_api_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserRequest) GetAuthId() int64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

func (x *UpdateUserRequest) GetName() *wrappers.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateUserRequest) GetBio() *wrappers.StringValue {
	if x != nil {
		return x.Bio
	}
	return nil
}

func (x *UpdateUserRequest) GetSex() *wrappers.StringValue {
	if x != nil {
		return x.Sex
	}
	return nil
}

func (x *UpdateUserRequest) GetBirthdate() *timestamp.Timestamp {
	if x != nil {
		return x.Birthdate
	}
	return nil
}

func (x *UpdateUserRequest) GetPhone() *wrappers.StringValue {
	if x != nil {
		return x.Phone
	}
	return nil
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_v1_user_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_api_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateProfilePictureRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AuthId         int64                  `protobuf:"varint,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	ProfilePicture string                 `protobuf:"bytes,2,opt,name=profile_picture,json=profilePicture,proto3" json:"profile_picture,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateProfilePictureRequest) Reset() {
	*x = UpdateProfilePictureRequest{}
	mi := &file_v1_user_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfilePictureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfilePictureRequest) ProtoMessage() {}

func (x *UpdateProfilePictureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfilePictureRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfilePictureRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_api_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProfilePictureRequest) GetAuthId() int64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

func (x *UpdateProfilePictureRequest) GetProfilePicture() string {
	if x != nil {
		return x.ProfilePicture
	}
	return ""
}

type UpdateProfilePictureResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProfilePicture string                 `protobuf:"bytes,1,opt,name=profile_picture,json=profilePicture,proto3" json:"profile_picture,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateProfilePictureResponse) Reset() {
	*x = UpdateProfilePictureResponse{}
	mi := &file_v1_user_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfilePictureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfilePictureResponse) ProtoMessage() {}

func (x *UpdateProfilePictureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfilePictureResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfilePictureResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_api_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProfilePictureResponse) GetProfilePicture() string {
	if x != nil {
		return x.ProfilePicture
	}
	return ""
}

var File_v1_user_api_proto protoreflect.FileDescriptor

const file_v1_user_api_proto_rawDesc = "" +
	"\n" +
	"\x11v1/user_api.proto\x12\auser.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xb5\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x03bio\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x03bio\x12.\n" +
	"\x03sex\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x03sex\x128\n" +
	"\tbirthdate\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tbirthdate\x122\n" +
	"\x05phone\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x05phone\x12E\n" +
	"\x0fprofile_picture\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\x0eprofilePicture\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8e\x02\n" +
	"\x11UpsertUserRequest\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\x03R\x06authId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x03bio\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x03bio\x12.\n" +
	"\x03sex\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x03sex\x128\n" +
	"\tbirthdate\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tbirthdate\x122\n" +
	"\x05phone\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x05phone\"7\n" +
	"\x12UpsertUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\x03R\x06authId\"4\n" +
	"\x0fGetUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\"\xac\x02\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\x03R\x06authId\x120\n" +
	"\x04name\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x04name\x12.\n" +
	"\x03bio\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x03bio\x12.\n" +
	"\x03sex\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x03sex\x128\n" +
	"\tbirthdate\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tbirthdate\x122\n" +
	"\x05phone\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x05phone\"7\n" +
	"\x12UpdateUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\"_\n" +
	"\x1bUpdateProfilePictureRequest\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\x03R\x06authId\x12'\n" +
	"\x0fprofile_picture\x18\x02 \x01(\tR\x0eprofilePicture\"G\n" +
	"\x1cUpdateProfilePictureResponse\x12'\n" +
	"\x0fprofile_picture\x18\x01 \x01(\tR\x0eprofilePicture2\xbe\x02\n" +
	"\vUserService\x12E\n" +
	"\n" +
	"UpsertUser\x12\x1a.user.v1.UpsertUserRequest\x1a\x1b.user.v1.UpsertUserResponse\x12<\n" +
	"\aGetUser\x12\x17.user.v1.GetUserRequest\x1a\x18.user.v1.GetUserResponse\x12E\n" +
	"\n" +
	"UpdateUser\x12\x1a.user.v1.UpdateUserRequest\x1a\x1b.user.v1.UpdateUserResponse\x12c\n" +
	"\x14UpdateProfilePicture\x12$.user.v1.UpdateProfilePictureRequest\x1a%.user.v1.UpdateProfilePictureResponseB?Z=github.com/ritchieridanko/pasarly/backend/shared/apis/v1;apisb\x06proto3"

var (
	file_v1_user_api_proto_rawDescOnce sync.Once
	file_v1_user_api_proto_rawDescData []byte
)

func file_v1_user_api_proto_rawDescGZIP() []byte {
	file_v1_user_api_proto_rawDescOnce.Do(func() {
		file_v1_user_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_user_api_proto_rawDesc), len(file_v1_user_api_proto_rawDesc)))
	})
	return file_v1_user_api_proto_rawDescData
}

var file_v1_user_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_v1_user_api_proto_goTypes = []any{
	(*User)(nil),                         // 0: user.v1.User
	(*UpsertUserRequest)(nil),            // 1: user.v1.UpsertUserRequest
	(*UpsertUserResponse)(nil),           // 2: user.v1.UpsertUserResponse
	(*GetUserRequest)(nil),               // 3: user.v1.GetUserRequest
	(*GetUserResponse)(nil),              // 4: user.v1.GetUserResponse
	(*UpdateUserRequest)(nil),            // 5: user.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),           // 6: user.v1.UpdateUserResponse
	(*UpdateProfilePictureRequest)(nil),  // 7: user.v1.UpdateProfilePictureRequest
	(*UpdateProfilePictureResponse)(nil), // 8: user.v1.UpdateProfilePictureResponse
	(*wrappers.StringValue)(nil),         // 9: google.protobuf.StringValue
	(*timestamp.Timestamp)(nil),          // 10: google.protobuf.Timestamp
}
var file_v1_user_api_proto_depIdxs = []int32{
	9,  // 0: user.v1.User.bio:type_name -> google.protobuf.StringValue
	9,  // 1: user.v1.User.sex:type_name -> google.protobuf.StringValue
	10, // 2: user.v1.User.birthdate:type_name -> google.protobuf.Timestamp
	9,  // 3: user.v1.User.phone:type_name -> google.protobuf.StringValue
	9,  // 4: user.v1.User.profile_picture:type_name -> google.protobuf.StringValue
	10, // 5: user.v1.User.created_at:type_name -> google.protobuf.Timestamp
	10, // 6: user.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 7: user.v1.UpsertUserRequest.bio:type_name -> google.protobuf.StringValue
	9,  // 8: user.v1.UpsertUserRequest.sex:type_name -> google.protobuf.StringValue
	10, // 9: user.v1.UpsertUserRequest.birthdate:type_name -> google.protobuf.Timestamp
	9,  // 10: user.v1.UpsertUserRequest.phone:type_name -> google.protobuf.StringValue
	0,  // 11: user.v1.UpsertUserResponse.user:type_name -> user.v1.User
	0,  // 12: user.v1.GetUserResponse.user:type_name -> user.v1.User
	9,  // 13: user.v1.UpdateUserRequest.name:type_name -> google.protobuf.StringValue
	9,  // 14: user.v1.UpdateUserRequest.bio:type_name -> google.protobuf.StringValue
	9,  // 15: user.v1.UpdateUserRequest.sex:type_name -> google.protobuf.StringValue
	10, // 16: user.v1.UpdateUserRequest.birthdate:type_name -> google.protobuf.Timestamp
	9,  // 17: user.v1.UpdateUserRequest.phone:type_name -> google.protobuf.StringValue
	0,  // 18: user.v1.UpdateUserResponse.user:type_name -> user.v1.User
	1,  // 19: user.v1.UserService.UpsertUser:input_type -> user.v1.UpsertUserRequest
	3,  // 20: user.v1.UserService.GetUser:input_type -> user.v1.GetUserRequest
	5,  // 21: user.v1.UserService.UpdateUser:input_type -> user.v1.UpdateUserRequest
	7,  // 22: user.v1.UserService.UpdateProfilePicture:input_type -> user.v1.UpdateProfilePictureRequest
	2,  // 23: user.v1.UserService.UpsertUser:output_type -> user.v1.UpsertUserResponse
	4,  // 24: user.v1.UserService.GetUser:output_type -> user.v1.GetUserResponse
	6,  // 25: user.v1.UserService.UpdateUser:output_type -> user.v1.UpdateUserResponse
	8,  // 26: user.v1.UserService.UpdateProfilePicture:output_type -> user.v1.UpdateProfilePictureResponse
	23, // [23:27] is the sub-list for method output_type
	19, // [19:23] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_v1_user_api_proto_init() }
func file_v1_user_api_proto_init() {
	if File_v1_user_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_user_api_proto_rawDesc), len(file_v1_user_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_user_api_proto_goTypes,
		DependencyIndexes: file_v1_user_api_proto_depIdxs,
		MessageInfos:      file_v1_user_api_proto_msgTypes,
	}.Build()
	File_v1_user_api_proto = out.File
	file_v1_user_api_proto_goTypes = nil
	file_v1_user_api_proto_depIdxs = nil
}
