// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: v1/user_address_api.proto

package apis

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Notes         *wrappers.StringValue  `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,6,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Country       string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	Subdivision_1 *wrappers.StringValue  `protobuf:"bytes,8,opt,name=subdivision_1,json=subdivision1,proto3" json:"subdivision_1,omitempty"`
	Subdivision_2 *wrappers.StringValue  `protobuf:"bytes,9,opt,name=subdivision_2,json=subdivision2,proto3" json:"subdivision_2,omitempty"`
	Subdivision_3 *wrappers.StringValue  `protobuf:"bytes,10,opt,name=subdivision_3,json=subdivision3,proto3" json:"subdivision_3,omitempty"`
	Subdivision_4 *wrappers.StringValue  `protobuf:"bytes,11,opt,name=subdivision_4,json=subdivision4,proto3" json:"subdivision_4,omitempty"`
	Street        string                 `protobuf:"bytes,12,opt,name=street,proto3" json:"street,omitempty"`
	Postcode      string                 `protobuf:"bytes,13,opt,name=postcode,proto3" json:"postcode,omitempty"`
	Latitude      float64                `protobuf:"fixed64,14,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,15,opt,name=longitude,proto3" json:"longitude,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAddress) Reset() {
	*x = UserAddress{}
	mi := &file_v1_user_address_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddress) ProtoMessage() {}

func (x *UserAddress) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_address_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAddress.ProtoReflect.Descriptor instead.
func (*UserAddress) Descriptor() ([]byte, []int) {
	return file_v1_user_address_api_proto_rawDescGZIP(), []int{0}
}

func (x *UserAddress) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserAddress) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *UserAddress) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserAddress) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UserAddress) GetNotes() *wrappers.StringValue {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *UserAddress) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *UserAddress) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UserAddress) GetSubdivision_1() *wrappers.StringValue {
	if x != nil {
		return x.Subdivision_1
	}
	return nil
}

func (x *UserAddress) GetSubdivision_2() *wrappers.StringValue {
	if x != nil {
		return x.Subdivision_2
	}
	return nil
}

func (x *UserAddress) GetSubdivision_3() *wrappers.StringValue {
	if x != nil {
		return x.Subdivision_3
	}
	return nil
}

func (x *UserAddress) GetSubdivision_4() *wrappers.StringValue {
	if x != nil {
		return x.Subdivision_4
	}
	return nil
}

func (x *UserAddress) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *UserAddress) GetPostcode() string {
	if x != nil {
		return x.Postcode
	}
	return ""
}

func (x *UserAddress) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UserAddress) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UserAddress) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserAddress) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateUserAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthId        int64                  `protobuf:"varint,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Notes         *wrappers.StringValue  `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,6,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Country       string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	Subdivision_1 *wrappers.StringValue  `protobuf:"bytes,8,opt,name=subdivision_1,json=subdivision1,proto3" json:"subdivision_1,omitempty"`
	Subdivision_2 *wrappers.StringValue  `protobuf:"bytes,9,opt,name=subdivision_2,json=subdivision2,proto3" json:"subdivision_2,omitempty"`
	Subdivision_3 *wrappers.StringValue  `protobuf:"bytes,10,opt,name=subdivision_3,json=subdivision3,proto3" json:"subdivision_3,omitempty"`
	Subdivision_4 *wrappers.StringValue  `protobuf:"bytes,11,opt,name=subdivision_4,json=subdivision4,proto3" json:"subdivision_4,omitempty"`
	Street        string                 `protobuf:"bytes,12,opt,name=street,proto3" json:"street,omitempty"`
	Postcode      string                 `protobuf:"bytes,13,opt,name=postcode,proto3" json:"postcode,omitempty"`
	Latitude      float64                `protobuf:"fixed64,14,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,15,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserAddressRequest) Reset() {
	*x = CreateUserAddressRequest{}
	mi := &file_v1_user_address_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserAddressRequest) ProtoMessage() {}

func (x *CreateUserAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_address_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateUserAddressRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_address_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserAddressRequest) GetAuthId() int64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

func (x *CreateUserAddressRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *CreateUserAddressRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateUserAddressRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateUserAddressRequest) GetNotes() *wrappers.StringValue {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *CreateUserAddressRequest) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *CreateUserAddressRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateUserAddressRequest) GetSubdivision_1() *wrappers.StringValue {
	if x != nil {
		return x.Subdivision_1
	}
	return nil
}

func (x *CreateUserAddressRequest) GetSubdivision_2() *wrappers.StringValue {
	if x != nil {
		return x.Subdivision_2
	}
	return nil
}

func (x *CreateUserAddressRequest) GetSubdivision_3() *wrappers.StringValue {
	if x != nil {
		return x.Subdivision_3
	}
	return nil
}

func (x *CreateUserAddressRequest) GetSubdivision_4() *wrappers.StringValue {
	if x != nil {
		return x.Subdivision_4
	}
	return nil
}

func (x *CreateUserAddressRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CreateUserAddressRequest) GetPostcode() string {
	if x != nil {
		return x.Postcode
	}
	return ""
}

func (x *CreateUserAddressRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateUserAddressRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type CreateUserAddressResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Address           *UserAddress           `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	OldPrimaryAddress *UserAddress           `protobuf:"bytes,2,opt,name=old_primary_address,json=oldPrimaryAddress,proto3" json:"old_primary_address,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateUserAddressResponse) Reset() {
	*x = CreateUserAddressResponse{}
	mi := &file_v1_user_address_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserAddressResponse) ProtoMessage() {}

func (x *CreateUserAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_address_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserAddressResponse.ProtoReflect.Descriptor instead.
func (*CreateUserAddressResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_address_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserAddressResponse) GetAddress() *UserAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *CreateUserAddressResponse) GetOldPrimaryAddress() *UserAddress {
	if x != nil {
		return x.OldPrimaryAddress
	}
	return nil
}

type GetAllUserAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthId        int64                  `protobuf:"varint,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUserAddressesRequest) Reset() {
	*x = GetAllUserAddressesRequest{}
	mi := &file_v1_user_address_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUserAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUserAddressesRequest) ProtoMessage() {}

func (x *GetAllUserAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_address_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUserAddressesRequest.ProtoReflect.Descriptor instead.
func (*GetAllUserAddressesRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_address_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllUserAddressesRequest) GetAuthId() int64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

type GetAllUserAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*UserAddress         `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUserAddressesResponse) Reset() {
	*x = GetAllUserAddressesResponse{}
	mi := &file_v1_user_address_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUserAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUserAddressesResponse) ProtoMessage() {}

func (x *GetAllUserAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_address_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUserAddressesResponse.ProtoReflect.Descriptor instead.
func (*GetAllUserAddressesResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_address_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllUserAddressesResponse) GetAddresses() []*UserAddress {
	if x != nil {
		return x.Addresses
	}
	return nil
}

var File_v1_user_address_api_proto protoreflect.FileDescriptor

const file_v1_user_address_api_proto_rawDesc = "" +
	"\n" +
	"\x19v1/user_address_api.proto\x12\auser.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xc4\x05\n" +
	"\vUserAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x122\n" +
	"\x05notes\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x05notes\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x06 \x01(\bR\tisPrimary\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12A\n" +
	"\rsubdivision_1\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\fsubdivision1\x12A\n" +
	"\rsubdivision_2\x18\t \x01(\v2\x1c.google.protobuf.StringValueR\fsubdivision2\x12A\n" +
	"\rsubdivision_3\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\fsubdivision3\x12A\n" +
	"\rsubdivision_4\x18\v \x01(\v2\x1c.google.protobuf.StringValueR\fsubdivision4\x12\x16\n" +
	"\x06street\x18\f \x01(\tR\x06street\x12\x1a\n" +
	"\bpostcode\x18\r \x01(\tR\bpostcode\x12\x1a\n" +
	"\blatitude\x18\x0e \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x0f \x01(\x01R\tlongitude\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe4\x04\n" +
	"\x18CreateUserAddressRequest\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\x03R\x06authId\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x122\n" +
	"\x05notes\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x05notes\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x06 \x01(\bR\tisPrimary\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12A\n" +
	"\rsubdivision_1\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\fsubdivision1\x12A\n" +
	"\rsubdivision_2\x18\t \x01(\v2\x1c.google.protobuf.StringValueR\fsubdivision2\x12A\n" +
	"\rsubdivision_3\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\fsubdivision3\x12A\n" +
	"\rsubdivision_4\x18\v \x01(\v2\x1c.google.protobuf.StringValueR\fsubdivision4\x12\x16\n" +
	"\x06street\x18\f \x01(\tR\x06street\x12\x1a\n" +
	"\bpostcode\x18\r \x01(\tR\bpostcode\x12\x1a\n" +
	"\blatitude\x18\x0e \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x0f \x01(\x01R\tlongitude\"\x91\x01\n" +
	"\x19CreateUserAddressResponse\x12.\n" +
	"\aaddress\x18\x01 \x01(\v2\x14.user.v1.UserAddressR\aaddress\x12D\n" +
	"\x13old_primary_address\x18\x02 \x01(\v2\x14.user.v1.UserAddressR\x11oldPrimaryAddress\"5\n" +
	"\x1aGetAllUserAddressesRequest\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\x03R\x06authId\"Q\n" +
	"\x1bGetAllUserAddressesResponse\x122\n" +
	"\taddresses\x18\x01 \x03(\v2\x14.user.v1.UserAddressR\taddresses2\xca\x01\n" +
	"\x12UserAddressService\x12V\n" +
	"\rCreateAddress\x12!.user.v1.CreateUserAddressRequest\x1a\".user.v1.CreateUserAddressResponse\x12\\\n" +
	"\x0fGetAllAddresses\x12#.user.v1.GetAllUserAddressesRequest\x1a$.user.v1.GetAllUserAddressesResponseB?Z=github.com/ritchieridanko/pasarly/backend/shared/apis/v1;apisb\x06proto3"

var (
	file_v1_user_address_api_proto_rawDescOnce sync.Once
	file_v1_user_address_api_proto_rawDescData []byte
)

func file_v1_user_address_api_proto_rawDescGZIP() []byte {
	file_v1_user_address_api_proto_rawDescOnce.Do(func() {
		file_v1_user_address_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_user_address_api_proto_rawDesc), len(file_v1_user_address_api_proto_rawDesc)))
	})
	return file_v1_user_address_api_proto_rawDescData
}

var file_v1_user_address_api_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_user_address_api_proto_goTypes = []any{
	(*UserAddress)(nil),                 // 0: user.v1.UserAddress
	(*CreateUserAddressRequest)(nil),    // 1: user.v1.CreateUserAddressRequest
	(*CreateUserAddressResponse)(nil),   // 2: user.v1.CreateUserAddressResponse
	(*GetAllUserAddressesRequest)(nil),  // 3: user.v1.GetAllUserAddressesRequest
	(*GetAllUserAddressesResponse)(nil), // 4: user.v1.GetAllUserAddressesResponse
	(*wrappers.StringValue)(nil),        // 5: google.protobuf.StringValue
	(*timestamp.Timestamp)(nil),         // 6: google.protobuf.Timestamp
}
var file_v1_user_address_api_proto_depIdxs = []int32{
	5,  // 0: user.v1.UserAddress.notes:type_name -> google.protobuf.StringValue
	5,  // 1: user.v1.UserAddress.subdivision_1:type_name -> google.protobuf.StringValue
	5,  // 2: user.v1.UserAddress.subdivision_2:type_name -> google.protobuf.StringValue
	5,  // 3: user.v1.UserAddress.subdivision_3:type_name -> google.protobuf.StringValue
	5,  // 4: user.v1.UserAddress.subdivision_4:type_name -> google.protobuf.StringValue
	6,  // 5: user.v1.UserAddress.created_at:type_name -> google.protobuf.Timestamp
	6,  // 6: user.v1.UserAddress.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 7: user.v1.CreateUserAddressRequest.notes:type_name -> google.protobuf.StringValue
	5,  // 8: user.v1.CreateUserAddressRequest.subdivision_1:type_name -> google.protobuf.StringValue
	5,  // 9: user.v1.CreateUserAddressRequest.subdivision_2:type_name -> google.protobuf.StringValue
	5,  // 10: user.v1.CreateUserAddressRequest.subdivision_3:type_name -> google.protobuf.StringValue
	5,  // 11: user.v1.CreateUserAddressRequest.subdivision_4:type_name -> google.protobuf.StringValue
	0,  // 12: user.v1.CreateUserAddressResponse.address:type_name -> user.v1.UserAddress
	0,  // 13: user.v1.CreateUserAddressResponse.old_primary_address:type_name -> user.v1.UserAddress
	0,  // 14: user.v1.GetAllUserAddressesResponse.addresses:type_name -> user.v1.UserAddress
	1,  // 15: user.v1.UserAddressService.CreateAddress:input_type -> user.v1.CreateUserAddressRequest
	3,  // 16: user.v1.UserAddressService.GetAllAddresses:input_type -> user.v1.GetAllUserAddressesRequest
	2,  // 17: user.v1.UserAddressService.CreateAddress:output_type -> user.v1.CreateUserAddressResponse
	4,  // 18: user.v1.UserAddressService.GetAllAddresses:output_type -> user.v1.GetAllUserAddressesResponse
	17, // [17:19] is the sub-list for method output_type
	15, // [15:17] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_v1_user_address_api_proto_init() }
func file_v1_user_address_api_proto_init() {
	if File_v1_user_address_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_user_address_api_proto_rawDesc), len(file_v1_user_address_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_user_address_api_proto_goTypes,
		DependencyIndexes: file_v1_user_address_api_proto_depIdxs,
		MessageInfos:      file_v1_user_address_api_proto_msgTypes,
	}.Build()
	File_v1_user_address_api_proto = out.File
	file_v1_user_address_api_proto_goTypes = nil
	file_v1_user_address_api_proto_depIdxs = nil
}
